name: manual deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'where to deploy to? beta, production or next'
        required: true
        default: production

jobs:
  createDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Deployment'
        uses: avakar/create-deployment@v1.0.2
        with:
          ref: ${{ github.sha }}
          task: deploy
          environment: ${{ github.event.inputs.environment }}
          required_contexts: docker,node
          payload: '{"value_files": ["./config/_common.yml","./config/${{ github.event.inputs.environment }}.yml"],"release": "bahn-expert-${{ github.event.inputs.environment }}","namespace": "marudor","track": "stable"}'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
